name: flutter_mobx_hooks
description: MobX hooks facilitator for Flutter
version: 1.0.0
homepage: https://github.com/rrousselGit/flutter_hooks
#once flutter_hook is published to pub remove path and this to user proper version
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
    path: ../flutter_hooks
  mobx: '>=2.0.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
